### PR TITLE
rewrite/sendMessage

### PR DESCRIPTION
**Pull request by atlas-ark**
Improved indentation
New sendMessage

### CODE REVIEW

**Review by giulioc008 — APPROVED** [review]

**Review by giulioc008 — CHANGES_REQUESTED** [review]
@atlas-ark 
- [ ] Add a newline between the 53-th and the 54-th row
- [ ] convert `true` to `TRUE`
- [ ] convert `false` to `FALSE`
- [ ] Add a space after the `,` at the 75-th row

**Comment by atlas-ark** [comment]
Lol ahahahah

**Comment by atlas-ark** [comment]
Done!

**Comment by atlas-ark** [comment]
Done!

**Review by giulioc008 — APPROVED** [review]

**Pull request merged**
